### PR TITLE
add line number offset functionality

### PR DESCRIPTION
**Pull request by pjebs**

### CODE REVIEW

**Review by metonym — COMMENTED** [review]
Thanks for taking the time to submit a PR.

Can the prop name be more descriptive, like `startingLineNumber`?

**Comment by pjebs** [comment]
@metonym done

**Review by metonym — APPROVED** [review]
Looks great, thanks!

**Comment by metonym** [comment]
Released in [v7.1.1](https://github.com/metonym/svelte-highlight/releases/tag/v7.1.1)

**Pull request merged**
